name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #git history for sonarqube
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Short SHA with git rev-parse
        id: get_short_sha_git
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo $SHORT_SHA
      - name: Run tests and extract reports
        run: |
          docker build --target test -t python-app-test .
          docker create --name temp-container python-app-test
          docker cp temp-container:/app/coverage-report ./coverage-report
          docker rm temp-container
      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: coverage-report/
      - name: Build and push prod image
        uses: docker/build-push-action@v6
        with:
          target: production
          push: true
          tags: trestianstewart/python-app:${{ steps.get_short_sha_git.outputs.SHORT_SHA }}
    outputs:
      commit_id: ${{ steps.get_short_sha_git.outputs.SHORT_SHA }}
  cd-staging:
    needs: ci
    runs-on: self-hosted
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update image tag
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          sed -i "s/tag: \".*\"/tag: \"${{needs.ci.outputs.commit_id}}\"/" charts/python-app/values-staging.yaml
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'
      - name: Download to ArgoCD CLI
        shell: bash
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
      - name: Authenticate to ArgoCD server & Deploy to Staging
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app-staging
  cd-production:
    needs: ci
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update image tag
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          sed -i "s/tag: \".*\"/tag: \"${{needs.ci.outputs.commit_id}}\"/" charts/python-app/values-production.yaml
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'
      - name: Download to ArgoCD CLI
        shell: bash
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
      # - name: Authenticate to ArgoCD server & Deploy to Production
      #   shell: bash
      #   run: |
      #     argocd login argocd.production.local:443 \
      #     --insecure \
      #     --grpc-web \
      #     --username admin \
      #     --password ${{ secrets.ARGOCD_PROD_PASSWORD }}
      #     argocd app sync python-app-production
